# Generated by Django 5.2.3 on 2025-07-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.TextField(blank=True)),
                ('gpu', models.TextField(blank=True)),
                ('cpu', models.TextField(blank=True)),
                ('ram', models.TextField(blank=True)),
                ('power_supply', models.TextField(blank=True)),
                ('memory', models.TextField(blank=True)),
                ('cooler', models.TextField(blank=True)),
                ('case', models.TextField(blank=True)),
                ('motherboard', models.TextField(blank=True)),
            ],
        ),
    ]
