# Generated by Django 5.2.3 on 2025-07-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplectPCapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='case_market',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc',
            name='cooler_market',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc',
            name='cpu_market',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc',
            name='gpu_market',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc',
            name='memory_market',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc',
            name='motherboard_market',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc',
            name='power_supply_market',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc',
            name='ram_market',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='case',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='cooler',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='cpu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='gpu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='memory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='motherboard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='power_supply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='ram',
            field=models.TextField(blank=True, null=True),
        ),
    ]
